### ISSUE TITLE
Parse entire Component code to python 3.5 standards

### ISSUE THREAD

**Issue by rafaelvfalc** [ufcg-lsd/asperathos-visualizer#10]
The End Of Life for Python 2.7 will happen in 2020. Therefore it will be necessary effort to parse the entire component code to Python 3.5. This is a huge and necessary modification, and it is necessary attention to check if the entire component behavior is working as expected (The unit and integration test will help a lot to solve this issue).

**Comment by armstrongmsg** [comment]
Fixed on #27
